- name: Setup vector
  hosts: vector
  become: yes
  roles:
    - vector-role
  gather_facts: no

- name: Setup lighthouse
  hosts: lighthouse
  become: yes
  roles:
    - lighthouse-role
  gather_facts: no
